= brr-base-tf-resources
:toc:

[NOTE]
This is not the cleanest repo I have ever written so there may be some visible kruft around.

[TIP]
Look at the branches of this project. One is configured for Terraform, another is configured for OpenTofu and there are slight variations between the two

The goal of this repo is to provide a complete working template for new cloud account setups including base CI jobs to facilitate clear and easy setup and configuration.

Eventually I hope to have templates for multiple cloud providers. As it currently stands all projects are written with Aws in mind and are contained under the aws folder.

== The various ways to deploy EKS

The `002-setup-eks` project contains multiple valid ways in which to set up and configure your eks cluster. However, these various examples are in varying states of working order. Minimally all projects will successfully deploy an EKS cluster to Aws. See details below for state ...

* `001`
** Fully working as described in read me
** Can deploy argo
* `002`
** Works like project `001`
** Pod identity is not fully configured
* `003`
** Auto mode is enabled
** No node groups are created
** So far all deployments have failed taking to long
** Authentication is the same as project `001`
* `004`
** Auto mode is enabled
** No node groups are created
** So far all deployments have failed taking to long
** Pod identity is not fully configured
** Authentication is the same as project `001`
* `005`
** Uses HashiCorp provided EKS Module
** Deploys cluster but fails to create node groups
** DOES NOT CURRENTLY WORK
* `006`
** Uses HashiCorp provided EKS Module
** Deploys cluster but fails to create node groups
** DOES NOT CURRENTLY WORK

[NOTE]
Please reference the sub-readmes in each of the specified projects.

== Aws

=== Directory structure

This project could _technically_ be vastly simplified and all Terraform/OpenTofu projects could be placed directly under the `aws` folder. This is due to the fact that all these projects are configured in such a way that account and environments can be passed into them and executed idempotently across accounts and regions.

However, this becomes an issue when executing locally due to how Terraform/OpenTofu maintains its state. In example if all the projects are just under `aws` and I want to execute them from my machine to both dev and prod; whatever the second execution is will try to overwrite the first executions state. For this reason Terraform/OpenTofu projects must be duplicated per account and or region.

[NOTE]
Some of this can be remediated by only executing in CI and using OpenTofu instead of Terraform as OpenTofu allows for variables in the `terraform` block, meaning that the path to where the state is stored can be changed programmatically.

== Azure

- TODO

=== Directory structure

== GCP

- TODO

=== Directory structure

== Deployment Instructions

The following is the order in which projects need to be deployed in order to work correctly.

=== 001-once-per-account / 001-setup-oidc-provider

When setting up a new account this is the first project that needs to be executed if you are using GitHub

== GitHub Workflows

Currently, there is some variation in how workflows work, being that this is a personal project not all workflow operations have been extended to all files.

=== Static Analysis

This job runs TFLint, Trivy (TFSec), and Checkov. This runs on every push for all projects and all other project execution should be dependent on this Workflow passing.

=== VPC Deploy / Destroy

This workflow pair is probably the most built out and demonstrates a number of additional configuration that is not currently built into all the other jobs.

The deploy job verifies that the linting results passed and that the input from the user executing the job is valid prior to creating the vpc(s).

Additionally, there is an environment `all` option which will allow you to deploy to all configured regions for a given environment. I.e. if dev is configured to deploy to us-east-2 and us-west-2 you can select the `dev / all` option and deploy to both at the same time.

While the `all` option is semi convenient for me, I am unsure if this is or would be a good idea for a production level setup. This option required a fair amount of thinking and introduced a number of edge cases and hard coded values into the GH Workflow that would otherwise have not existed. I am not confident that the extra work and complexity is worth the convenience of having the option available. Especially, considering that deploying to multiple environments at the same time in a work / production system will be an exceptionally rare occurrence.

Good or bad I have created the example here for reference.

[NOTE]
The destroy workflow does not check the linting results as there is no reason for it to care. It will just go through and destroy the necessary resources.

=== EKS Deploy / Destroy


=== Nginx Deploy / Destroy


=== ArgoCD Deploy / Destroy

== Known Issues

* common - node group is not created or fails to attach to the cluster
** fix - unclear at this point
* common - incorrect authentication bridging the gap between iam and rbac
** fix - review project `001-eks-std-irsa` this shows how to correctly get roles created in Terraform/OpenTofu authorized to rbac

== Reference

* https://spacelift.io/blog/github-actions-terraform
* https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows#passing-inputs-and-secrets-to-a-reusable-workflow
* https://spacelift.io/blog/argocd-terraform
* https://dev.to/mechcloud_academy/eks-standard-vs-eks-auto-mode-the-evolutionary-leap-in-kubernetes-operations-287g
* https://dev.to/kelechiedeh/step-by-step-guide-creating-an-amazon-eks-cluster-using-terraform-5204
* https://medium.com/@cloudcommander/argocd-on-aws-eks-as-simple-as-ever-171ae71f3a37
** look at this one for deploying to argo
* https://medium.com/@Jitendra09/from-push-to-pull-why-github-actions-argocd-is-the-devops-duo-you-need-in-2025-a38978f3dafe
* https://medium.com/@anujkishor1994/streamlining-multi-environment-argocd-management-centralized-control-for-multiple-applications-7e11a6d70c42
** this is the one to review for multi environment management
* https://7tonshark.com/posts/organize-github-workflows/
** How to organize github workflows
* https://blog.saintmalik.me/argocd-on-kubernetes-cluster/
* https://registry.terraform.io/modules/squareops/argocd/kubernetes/latest
** Module for creation
* https://dev.to/aws-builders/gitops-with-argocd-on-amazon-eks-using-terraform-a-complete-implementation-guide-1inc
** interesting as it sets argo up with a custom domain
*

== Legacy notes - not sure if useful

my local role arn

 * arn:aws:sts::792981815698:assumed-role/AWSReservedSSO_AdministratorAccess_eeb8e63974797d2b/brrAwsIdentity

* https://manski.net/articles/github/actions/cheat-sheet
* https://medium.com/@ayushishrot/how-to-automate-terraform-deployments-with-github-actions-a-step-by-step-guide-3af1ec203bb5
*

aws eks create-access-entry \
--cluster-name my-eks-cluster-example-1-xNRn9CZU \
--principal-arn arn:aws:iam::792981815698:role/aws-reserved/sso.amazonaws.com/us-east-2/AWSReservedSSO_AdministratorAccess_eeb8e63974797d2b \
--type STANDARD \
--region us-east-2


aws eks create-access-entry \
--cluster-name my-eks-cluster-example-1-f9tbDfzd \
--principal-arn arn:aws:iam::792981815698:role/aws-reserved/sso.amazonaws.com/us-east-2/AWSReservedSSO_AdministratorAccess_eeb8e63974797d2b \
--type STANDARD \
--region us-east-2

aws eks create-access-entry \
--cluster-name my-eks-cluster-example-1-f9tbDfzd \
--principal-arn arn:aws:iam::792981815698:role/github_oidc_ci_assume_role \
--type STANDARD \
--region us-east-2

// oidc role trust policy

{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Principal": {
"Federated": "arn:aws:iam::792981815698:oidc-provider/token.actions.githubusercontent.com"
},
"Action": "sts:AssumeRoleWithWebIdentity",
"Condition": {
"StringEquals": {
"token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
},
"StringLike": {
"token.actions.githubusercontent.com:sub": "repo:benrhine/brr-base-tf-resources:ref:refs/heads/main"
}
}
}
]
}

{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Action": [
"eks:*"
],
"Resource": "*"
}
]
}
